/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotto;
import java.util.*;
/**
 *
 * @author x15572883
 */
public class LottoMain extends javax.swing.JFrame {
        int[]lottoUser = new int[5];
        int[]lottoNum = new int[5];
    /**
     * Creates new form LottoMain
     */
    public LottoMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        InputJlabel = new javax.swing.JLabel();
        InputTF = new javax.swing.JTextField();
        CheckBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        ResultJlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        InputJlabel.setText("User Input");
        jPanel1.add(InputJlabel);
        InputJlabel.setBounds(10, 70, 80, 14);
        jPanel1.add(InputTF);
        InputTF.setBounds(100, 70, 143, 20);

        CheckBtn.setBackground(new java.awt.Color(0, 204, 204));
        CheckBtn.setText("Check");
        CheckBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBtnActionPerformed(evt);
            }
        });
        jPanel1.add(CheckBtn);
        CheckBtn.setBounds(10, 130, 80, 23);

        BackBtn.setBackground(new java.awt.Color(0, 204, 204));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn);
        BackBtn.setBounds(115, 290, 110, 23);
        jPanel1.add(ResultJlabel);
        ResultJlabel.setBounds(100, 120, 155, 53);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Main Class.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 260, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FirstGui().setVisible(true);
        
         //System.exit(0);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void CheckBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBtnActionPerformed
        // TODO add your handling code here:
        String userNum = InputTF.getText();
        lottoUser[0]= Integer.parseInt(userNum);
        
        for(int i=0; i<5; i++){
            lottoNum[i]=(int)(Math.random()*39)+1;
            if(i !=0){
                for(int z = 1; z<=i; z++){
                    if(lottoNum[i]==lottoNum[z-1]){
                        i--;
                        z--;
                        
                        i++;
                    }
                }
            }
            
            
        }
        
        if(lottoUser[0]==lottoNum[0]){
            ResultJlabel.setText("Number Matched");
        }
        else{
            ResultJlabel.setText("Number Not Matched");
        }
    }//GEN-LAST:event_CheckBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CheckBtn;
    private javax.swing.JLabel InputJlabel;
    private javax.swing.JTextField InputTF;
    private javax.swing.JLabel ResultJlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
