/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lotto;



/**
 *
 * @author x15422362
 */

import java.awt.Container;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
public class Plus1GUI extends javax.swing.JFrame implements Serializable{
    
    int[] lotto = new int[5];

    /**
     * Creates new form Plus1GUI
     */
    public Plus1GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputTF = new javax.swing.JTextField();
        RandomTF = new javax.swing.JTextField();
        GenBtn = new javax.swing.JButton();
        TextJlabel = new javax.swing.JLabel();
        YesBtn = new javax.swing.JButton();
        NoBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        DisplayJlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("User Input");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 90, 100, 14);

        InputTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTFActionPerformed(evt);
            }
        });
        jPanel1.add(InputTF);
        InputTF.setBounds(30, 120, 135, 34);
        jPanel1.add(RandomTF);
        RandomTF.setBounds(30, 170, 135, 42);

        GenBtn.setBackground(new java.awt.Color(0, 204, 204));
        GenBtn.setText("Generate");
        GenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenBtnActionPerformed(evt);
            }
        });
        jPanel1.add(GenBtn);
        GenBtn.setBounds(30, 240, 135, 23);

        TextJlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextJlabel.setText("Did they match?");
        jPanel1.add(TextJlabel);
        TextJlabel.setBounds(210, 80, 128, 41);

        YesBtn.setBackground(new java.awt.Color(0, 204, 204));
        YesBtn.setText("Yes");
        YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(YesBtn);
        YesBtn.setBounds(210, 140, 70, 23);

        NoBtn.setBackground(new java.awt.Color(0, 204, 204));
        NoBtn.setText("No");
        NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(NoBtn);
        NoBtn.setBounds(310, 140, 70, 23);

        BackBtn.setBackground(new java.awt.Color(0, 204, 204));
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(BackBtn);
        BackBtn.setBounds(295, 320, 100, 23);

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(173, 320, 90, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lotto plus.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 4, 430, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayJlabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(DisplayJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FirstGui().setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void GenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenBtnActionPerformed
        // TODO add your handling code here:
           for(int i=0;i<5;i++){
            lotto[i]=(int)(Math.random()*39)+1;
            if(i !=0){
                for(int z = 1; z<= i; z++){
                if(lotto[i]==lotto[z-1]){
                    i--;
                    z--;
                    
                    i++;
                }
            }
            }
        }
            for(int p = 0; p<lotto.length;p++){
            RandomTF.setText(String.valueOf(lotto[0])+","+String.valueOf(lotto[1])+","+String.valueOf(lotto[2])+","+String.valueOf(lotto[3])+","+String.valueOf(lotto[4]));
        }
    }//GEN-LAST:event_GenBtnActionPerformed

    private void YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesBtnActionPerformed
        // TODO add your handling code here:
          if(lotto[0]==lotto[0]){
               showMessageDialog(null, "You win!");
          }
    }//GEN-LAST:event_YesBtnActionPerformed

    private void NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoBtnActionPerformed
        // TODO add your handling code here:
          if(lotto[0]==lotto[0]){
               showMessageDialog(null, "You lost! Better luck next time");
          }
    }//GEN-LAST:event_NoBtnActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
      File outFile;
      FileOutputStream fStream;
      ObjectOutputStream outStream;
      
      try{
          outFile = new File("output.dat");
          fStream = new FileOutputStream(outFile);
          outStream = new ObjectOutputStream(fStream);
          
          
          outStream.writeObject(lotto);
          
          JOptionPane.showMessageDialog(null, "File Written Suceesfully");
          
          outStream.close();
          
      }
      catch(IOException e){
          System.out.print(e);
      }
    }//GEN-LAST:event_saveActionPerformed

    private void InputTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plus1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plus1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plus1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plus1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plus1GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel DisplayJlabel;
    private javax.swing.JButton GenBtn;
    private javax.swing.JTextField InputTF;
    private javax.swing.JButton NoBtn;
    private javax.swing.JTextField RandomTF;
    private javax.swing.JLabel TextJlabel;
    private javax.swing.JButton YesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables

   
    
}
